### ISSUE TITLE
Breaks adsmpipe

### ISSUE THREAD

**Issue by stefanhh** [briner/tsm4ubuntu-12.04#2]
Hi

Nice script, one comment, the rename of /opt/tivoli to /opt/uau seems to break adsmpipe.  I would change it to /opt/tivoli again.

Regards
Stefan Thor Hreinsson
Basis

**Comment by briner** [comment]
As I do not know what is really adsmpipe, could you give me a bit more info about it and, if possible, a small exemple on how to use it.

**Comment by briner** [comment]
And notice also that you can change this value because it is defined as a value in the fonction:
define_variable()
and the variable name is:
OPT_PATH='opt/uau/tsm'

Regards

**Comment by briner** [comment]
no response.
