### ISSUE TITLE
Package naming convention

### ISSUE THREAD

**Issue by itsbo** [briner/tsm4ubuntu-12.04#4]
Hi,

I'd suggest you amend the package name with the System Architecture, like:

DEB_BUILD=${TSM_ROOT}/${DEBNAME}_${TSM_VER}-${DEB_VER}_amd64

this would be more conforming with the Debian package naming convention. Not that it is much of a problem but just something that struck me.

http://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html

Thank you for your good work.

**Comment by briner** [comment]
This package is actually dead. I saw you made the same comment for tsm2deb. I'm currently doing it and testing it.
