### ISSUE TITLE
missing en_US locale

### ISSUE THREAD

**Issue by itsbo** [briner/tsm4ubuntu-12.04#5]
Hi,

It is recommended to run the client with the "en_US" locale. Most modern Ubuntu systems do not have this though, they have "en_US.utf8". So my startup scripts check for this and generate the missing locale. Would that be something you think would be sensible to integrate into the packages?

note: got to set DSM_LANG first (not an official Variable by IBM just called by me that way)

```
DSM_LANG=en_US
```

```
checklocale() {
local ENLOCALE=`locale -a |grep $DSM_LANG|grep -v utf8` > /dev/null 2>&1
if [ -z "$ENLOCALE" ] ; then
        log_warning_msg "Missing locale, generating..."
        locale-gen $DSM_LANG > /dev/null 2>&1
fi
}
```

Edit: Regarding this, there is a paper by IBM about this here: http://www-01.ibm.com/support/docview.wss?uid=swg27013395

**Comment by briner** [comment]
hello,

As this script is dead, I've added it to tsm2deb in the (following patch)[https://github.com/briner/tsm2deb/commit/e02486125b71f8ff48998d37f22e3419e2ae58c1]

Thanks for your contribution.

**Comment by itsbo** [comment]
I changed my scripting a little in the meantime towards this:

```
local ENLOCALE=`locale -a |grep $DSM_LANG$|grep -v utf8` > /dev/null 2>&1
```

note the second "$", to search at the end of the string, otherwise it is possible to not detect the locale properly, as en_US.iso88591 would also match. I also put the whole thing into the postinstall script instead of the startscript.

**Comment by briner** [comment]
Thanks for the hint,

I've finally choosed to do

``` bash
local ENLOCALE=$(locale -a | grep -E  "^${DSM_LANG}$" &> /dev/null )
```

**Comment by itsbo** [comment]
I just noticed that Ubuntu does not use 

```
/etc/locale.gen
```

like you do in the patch. Ubuntu uses files under

```
/var/lib/locales/supported.d/
```

:-(

**Comment by briner** [comment]
okay.. hope it's the good one

``` bash
checklocale()
{
    local ENLOCALE=$(locale -a | grep -E  "^${DSM_LANG}$" &> /dev/null )
    if [ -z "$ENLOCALE" ] ; then
        log_warning_msg "Missing locale, generating ..."
        distrib=$(lsb_release -a | grep "Distributor ID:" | cut -d ":" -f2 | sed -r "s|^\s*(\S+)\s*$|\1|")
        if test ${distrib} = "Debian"
        then
            # on debian only
            # uncomment the en_US entry in /etc/locale.gen
            sed --in-place=.bkp.tsm -r "s|#\s*en_US(\s+)|en_US\1|g" /etc/locale.gen
            # if not, then add this manually
            if ! grep -Eq "en_US\s" /etc/locale.gen
            then
                echo "en_US ISO-8859-1" >> /etc/locale.gen
            fi
        fi
        locale-gen $DSM_LANG &> /dev/null
    fi
}
```
